export interface ExerciseSeedDefinition {
  slug: string;
  name: string;
  category: string;
  equipment?: string;
  requiresLoad?: boolean;
  summary: string;
  steps: string;
  safetyNotes?: string;
}

export const exerciseCatalogSeed: ExerciseSeedDefinition[] = [
  {
    slug: "depth-jumps",
    name: "Depth Jumps",
    category: "plyometrics",
    summary: "Salto pliometrico de alta intensidad buscando reaccion rapida en el contacto.",
    steps: "Bajar desde una caja, aterrizar con control y explotar hacia arriba minimizando la fase de amortizacion.",
    safetyNotes: "No usar carga externa y evitarlo en principiantes sin base previa.",
  },
  {
    slug: "side-to-side-box-jumps",
    name: "Side to Side Box Jumps",
    category: "plyometrics",
    equipment: "box",
    summary: "Saltos laterales sobre caja o superficie estable.",
    steps: "Mantener ritmo rapido, apoyo reactivo y alineacion de rodillas durante cada salto lateral.",
  },
  {
    slug: "weighted-explosions",
    name: "Weighted Explosions",
    category: "explosive-strength",
    equipment: "external load",
    requiresLoad: true,
    summary: "Movimiento explosivo con carga ajustable.",
    steps: "Aplicar la carga definida por el coach/admin y ejecutar cada repeticion a maxima velocidad tecnica.",
    safetyNotes: "Detener la serie cuando la velocidad caiga o la tecnica se degrade.",
  },
  {
    slug: "medicine-ball-approach",
    name: "Medicine Ball Approach",
    category: "power",
    equipment: "medicine ball",
    summary: "Trabajo de aproximacion y transferencia de potencia con balon medicinal.",
    steps: "Coordinar carrera o paso de aproximacion con lanzamiento o gesto explosivo segun prescripcion.",
  },
  {
    slug: "zig-zags",
    name: "Zig Zags",
    category: "agility",
    summary: "Desplazamiento reactivo con cambios de direccion cortos.",
    steps: "Mantener apoyos cortos, cadera activa y cambio de direccion rapido sin perder postura.",
  },
  {
    slug: "medicine-throws",
    name: "Medicine Throws",
    category: "power",
    equipment: "medicine ball",
    summary: "Lanzamientos explosivos con balon medicinal.",
    steps: "Usar un patron de lanzamiento definido por el coach y recuperar el control antes de repetir.",
  },
  {
    slug: "rim-jumps",
    name: "Rim Jumps",
    category: "jump-specific",
    equipment: "basketball rim",
    summary: "Saltos especificos buscando tocar tablero, red o aro.",
    steps: "Realizar cada intento con tecnica completa de salto y descansos suficientes entre repeticiones.",
  },
  {
    slug: "speed-rope",
    name: "Speed Rope",
    category: "conditioning",
    equipment: "jump rope",
    summary: "Trabajo de cuerda para activacion de tobillos y ritmo.",
    steps: "Usar intervalos cortos sin llegar a fatiga y mantener contactos rapidos y ligeros.",
  },
  {
    slug: "pws",
    name: "PWS",
    category: "recovery-nutrition",
    summary: "Post-workout snack o rutina post-entrenamiento.",
    steps: "Registrar la colacion o recovery prescrito despues de cada jornada, incluso en dias de descanso.",
  },
  {
    slug: "stretch-and-recover",
    name: "Stretch and Recover",
    category: "recovery",
    summary: "Bloque de estiramientos y recuperacion general.",
    steps: "Aplicar la secuencia de calentamiento, movilidad y estiramientos del manual segun el dia correspondiente.",
    safetyNotes: "Mantener los estiramientos sin dolor y respetar tiempos de recuperacion de 24-48 horas.",
  },
  {
    slug: "core-series",
    name: "Core Series",
    category: "core",
    summary: "Serie de trabajo abdominal y estabilizacion del tronco.",
    steps: "Completar la secuencia configurada en admin manteniendo control postural y respiracion.",
  },
  {
    slug: "upper-series",
    name: "Upper Series",
    category: "upper-body",
    summary: "Serie complementaria de tren superior.",
    steps: "Ejecutar los movimientos definidos para el tren superior sin interferir con la recuperacion de piernas.",
  },
  {
    slug: "off-day-exercises-only",
    name: "Off Day Exercises Only",
    category: "rest",
    summary: "Rutina ligera o indicaciones exclusivas para dia de descanso.",
    steps: "Mantener solo la actividad ligera prescrita y evitar carga intensa de piernas.",
  },
  {
    slug: "explosion-squats",
    name: "Explosion Squats",
    category: "strength",
    equipment: "barbell",
    requiresLoad: true,
    summary: "Sentadilla con intencion explosiva.",
    steps: "Mover la carga prescrita a maxima velocidad con tecnica solida y recorrido controlado.",
  },
  {
    slug: "explosion-calf-raises",
    name: "Explosion Calf Raises",
    category: "strength",
    equipment: "calf raise setup",
    requiresLoad: true,
    summary: "Elevaciones de gemelo con intencion explosiva.",
    steps: "Extender tobillos con potencia y controlar el retorno manteniendo estabilidad.",
  },
  {
    slug: "dead-lifts",
    name: "Dead Lifts",
    category: "strength",
    equipment: "barbell",
    requiresLoad: true,
    summary: "Patron de bisagra de cadera para fuerza posterior.",
    steps: "Mantener espalda neutra, tension total y acelerar la fase concentica segun prescripcion.",
  },
  {
    slug: "ham-curls",
    name: "Ham Curls",
    category: "strength",
    equipment: "machine or bands",
    summary: "Trabajo accesorio de isquiotibiales.",
    steps: "Controlar el rango y priorizar la tension muscular sin compensaciones de cadera.",
  },
  {
    slug: "in-place-lunges",
    name: "In Place Lunges",
    category: "strength",
    summary: "Zancadas en el sitio para fuerza unilateral.",
    steps: "Mantener tronco estable, rodilla alineada y profundidad consistente en ambos lados.",
  },
  {
    slug: "hang-cleans",
    name: "Hang Cleans",
    category: "olympic-lift",
    equipment: "barbell",
    requiresLoad: true,
    summary: "Levantamiento olimpico desde hang para potencia.",
    steps: "Ejecutar con tecnica validada, triple extension y recepcion controlada.",
    safetyNotes: "Requiere supervision tecnica y ajuste de carga por admin o coach.",
  },
  {
    slug: "knee-drives",
    name: "Knee Drives",
    category: "running-mechanics",
    summary: "Trabajo de impulso de rodilla y patron de carrera.",
    steps: "Conducir la rodilla con rapidez manteniendo cadera estable y brace del tronco.",
  },
  {
    slug: "sprints",
    name: "Sprints",
    category: "speed",
    summary: "Aceleraciones cortas de alta intensidad.",
    steps: "Ejecutar cada sprint con recuperacion suficiente y tecnica de salida limpia.",
  },
  {
    slug: "lunge-jumps",
    name: "Lunge Jumps",
    category: "plyometrics",
    summary: "Saltos pliometricos en patron de zancada.",
    steps: "Alternar piernas en el aire o entre repeticiones segun prescripcion, manteniendo aterrizaje estable.",
  },
  {
    slug: "1-leg-chair-rockets",
    name: "1 Leg Chair Rockets",
    category: "plyometrics",
    equipment: "chair or box",
    summary: "Trabajo unilateral explosivo con apoyo de silla o caja.",
    steps: "Usar apoyo estable, impulsar con una pierna y controlar cada aterrizaje antes de repetir.",
    safetyNotes: "Progresar solo con buena estabilidad de tobillo y rodilla.",
  },
  {
    slug: "spanish-squat-isometric",
    name: "Spanish Squat Isometric",
    category: "injury-prevention",
    equipment: "strap or band",
    summary: "Isometrico para tendon rotuliano y tolerancia de cuatriceps con bajo impacto.",
    steps: "Sentarse hacia atras con apoyo de cinta o correa, tibia vertical y tronco alto, manteniendo tension constante.",
    safetyNotes: "Suspender si aparece dolor punzante en la rodilla o perdida clara de postura.",
  },
  {
    slug: "split-squat-isometric",
    name: "Split Squat Isometric",
    category: "injury-prevention",
    summary: "Isometrico unilateral para controlar cadera, rodilla y pie.",
    steps: "Adoptar una zancada estable y sostener la posicion media sin colapsar la rodilla hacia dentro.",
  },
  {
    slug: "soleus-wall-sit-hold",
    name: "Soleus Wall Sit Hold",
    category: "injury-prevention",
    equipment: "wall",
    summary: "Trabajo isometrico de soleo y tobillo para preparar la rigidez del apoyo.",
    steps: "Mantener semiflexion de rodilla contra pared elevando ligeramente talones o empujando el antepie contra el suelo.",
  },
  {
    slug: "glute-bridge-isometric",
    name: "Glute Bridge Isometric",
    category: "posterior-chain",
    summary: "Puente de gluteo en isometria para activar cadena posterior sin carga agresiva.",
    steps: "Elevar cadera hasta alinear hombros, pelvis y rodillas, sosteniendo con abdomen activo.",
  },
  {
    slug: "snap-down-landing",
    name: "Snap Down Landing",
    category: "landing-mechanics",
    summary: "Caida rapida a posicion atletica para ensenar aterrizaje limpio y silencioso.",
    steps: "Extenderse alto, caer rapido a cuarto de sentadilla y estabilizar sin rebote extra.",
    safetyNotes: "Priorizar control de rodilla, cadera y pie antes de aumentar velocidad.",
  },
  {
    slug: "low-pogo-series",
    name: "Low Pogo Series",
    category: "elasticity",
    summary: "Serie de rebotes bajos para introducir rigidez de tobillo con poco impacto.",
    steps: "Hacer contactos cortos y verticales con rodillas suaves y tronco estable.",
    safetyNotes: "Cortar si el contacto deja de ser rapido o aparece molestia en aquiles o fascia plantar.",
  },
  {
    slug: "dead-bug-breathing",
    name: "Dead Bug Breathing",
    category: "core",
    summary: "Trabajo respiratorio y de estabilidad para fijar caja toracica y pelvis.",
    steps: "Presionar zona lumbar contra el suelo, exhalar largo y mover brazos o piernas sin perder brace.",
  },
  {
    slug: "side-plank-hold",
    name: "Side Plank Hold",
    category: "core",
    summary: "Plancha lateral isometrica para estabilidad frontal y lateral de tronco y pelvis.",
    steps: "Mantener una linea recta desde hombros hasta tobillos, empujando el suelo con el antebrazo.",
  },
  {
    slug: "ankle-mobility-flow",
    name: "Ankle Mobility Flow",
    category: "mobility",
    summary: "Secuencia suave de movilidad de tobillo y pie para preparar dorsiflexion y apoyo.",
    steps: "Alternar rodilla sobre punta, circulos de tobillo y trabajo de dedos con respiracion controlada.",
  },
];
