const EXERCISE_MAP: Record<string, string> = {
  // === FASE 1: ADAPTACIÓN Y SALUD TENDINOSA ===
  "Movilidad Dinámica": "world greatest stretch",
  "Depth Drops": "box jump down",
  "Bulgarian Split Squat": "dumbbell bulgarian split squat",
  "Push Ups Explosivas": "clap push up",
  "Nordic Curl Asistido": "self assisted nordic hamstring curl",
  "Plank con Toque de Hombros": "kneeling plank tap shoulder (male)",
  "Tibialis Raise": "tibialis anterior raise",
  "Estiramiento Estático": "subscapularis stretch",
  "Descanso Activo": "walk",
  "Pogo Jumps Nivel 1": "ankle hops plyo",
  "Goblet Squat": "dumbbell goblet squat",
  "Pull Ups": "pullup",
  "Deadlift Rumano": "barbell romanian deadlift",
  "Copenhague Plank": "copenhagen plank",
  "Calf Raises": "standing calf raise",
  "Face Pulls": "rope face pull",
  "Estiramiento y Movilidad": "yoga positions",
  "Saltos de Aproximación": "rocket jump",
  "Step Ups Explosivos": "box step up",
  "Dips": "triceps dip",
  "Glute Bridge Una Pierna": "single leg glute bridge",
  "Dead Bug": "dead bug",
  "Aterrizaje Monopodal": "single leg landing",

  // === FASE 2: RECLUTAMIENTO DE FUERZA MÁXIMA ===
  "Trap Bar Jump": "trap bar jump squat",
  "Sentadilla (Back Squat)": "barbell back squat",
  "Press Militar": "barbell standing overhead press",
  "Box Jump": "box jump",
  "Trap Bar Deadlift": "trap bar deadlift",
  "Pull Ups (Lastradas)": "weighted pullup",
  "Zancadas Caminando": "dumbbell walking lunge",
  "Step Up Cargado": "dumbbell box step up",
  "Press Banca": "barbell bench press",
  "Glute Bridge Barbell": "barbell glute bridge",
  "Aterrizaje Monopodal + Salto": "lateral bounds",

  // === FASE 3: CONVERSIÓN A EXPLOSIVIDAD ===
  "Max Approach Jump": "squat jump",
  "Depth Jumps (Reactivos)": "depth jump",
  "Power Clean": "barbell power clean",
  "Sprints de 10m": "run",
  "Assisted Jumps": "band assisted jump",
  "Push Press": "barbell push press",
  "Speed Deadlift": "barbell deadlift",
  "Single Leg Pogo Jumps": "single leg ankle hops",
  "Sprints de 20m": "run",
  "V-Ups Explosivos": "v-up"
};